name 'formatron_nginx'
version '0.1.1'
description 'Formatron Nginx cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/nginx-cookbook'
issues_url 'https://github.com/formatron/nginx-cookbook/issues'
supports 'ubuntu'
